name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm run format:fix

      - name: Lint
        run: pnpm run lint

      - name: Debug legacy files
        run: |
          echo "Checking for legacy Next.js files..."
          git ls-files | grep -Ei '(^|/)pages/_document\.(t|j)sx?$' || true
          git ls-files | grep -Ei '(^|/)(pages|src/pages)/404\.(t|j)sx?$' || true
          git ls-files | grep -Ei '(^|/)src/.*/_document\.(t|j)sx?$' || true

      - name: Run build
        run: pnpm build
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          API_URL: ${{ secrets.API_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
